// 跨域代理前缀
import { config } from '@/utils/common';
const BASE_URL = config.APP_API_AUTH_URL;
const OPEN_URL = config.APP_API_OPEN_URL;

console.log(config);
export default {
  LOGIN: `${BASE_URL}/sign-in`,
  USER_INFO: `${BASE_URL}/user-info`,
  USER_LIST: `${BASE_URL}/user-list`,
  USER_ADD: `${BASE_URL}/user-add`,
  USER_SAVE: `${BASE_URL}/user-save`,
  CHANGE_USER_STATE: `${BASE_URL}/change-user-state`,
  ROLE_LIST: `${BASE_URL}/role-list`,
  ROUTES: `${BASE_URL}/routes`,
  GOODS: `${BASE_URL}/goods`,
  GOODS_COLUMNS: `${BASE_URL}/columns`,
  USER_WELCOME: `${BASE_URL}/user-welcome`,
  WORK_ACTIVITY: `${BASE_URL}/work-activity`,
  WORK_TEAM: `${BASE_URL}/work-team`,
  WORK_PROJECT: `${BASE_URL}/work-projects`,
  FLOW_SMCAT: `${OPEN_URL}/fsm-flow-smcat`,
  FLOW_QUERY: `${OPEN_URL}/fsm-flow-query`,
  FLOW_START: `${OPEN_URL}/fsm-flow-start`,
  FLOW_ABORT: `${OPEN_URL}/fsm-flow-abort`,
  TASK_QUERY: `${OPEN_URL}/fsm-task-query`,
  TASK_SUBMIT: `${OPEN_URL}/fsm-task-submit`,
  DEMO_CALC: `${BASE_URL}/demo-calc`,
  DEMO_CALC1: `${BASE_URL}/demo-calc1`,
  DEMO_TBL_DATA: `${BASE_URL}/demo-table-data`,
  DEMO_TBL_DATA2: `${BASE_URL}/demo-table-data2`,
  PROJ_LIST: `${BASE_URL}/project/list`,
  PROJ_INFO: `${BASE_URL}/project/info`,
  PROJ_ADD: `${BASE_URL}/project/add`,
  PROJ_UPDATE: `${BASE_URL}/project/update`,
  PROJ_DELETE: `${BASE_URL}/project/delete`,
  DEPT_LIST: `${BASE_URL}/department/list`,
  DEPT_INFO: `${BASE_URL}/department/info`,
  DEPT_ADD: `${BASE_URL}/department/add`,
  DEPT_UPDATE: `${BASE_URL}/department/update`,
  DEPT_DELETE: `${BASE_URL}/department/delete`,
  DICT_LIST: `${BASE_URL}/dictionary/list`,
  DICT_INFO: `${BASE_URL}/dictionary/info`,
  DICT_ADD: `${BASE_URL}/dictionary/add`,
  DICT_UPDATE: `${BASE_URL}/dictionary/update`,
  DICT_DELETE: `${BASE_URL}/dictionary/delete`,
  USERSIGN_LIST: `${BASE_URL}/userSignature/list`,
  USERSIGN_INFO: `${BASE_URL}/userSignature/info`,
  USERSIGN_ADD: `${BASE_URL}/userSignature/add`,
  USERSIGN_UPDATE: `${BASE_URL}/userSignature/update`,
  USERSIGN_DELETE: `${BASE_URL}/userSignature/delete`,
  USERSIGN_PIC: `${BASE_URL}/userSignature/picture`,
  TRANSTEMPLATE_LIST: `${BASE_URL}/transTemplate/list`,
  TRANSTEMPLATE_INFO: `${BASE_URL}/transTemplate/info`,
  TRANSTEMPLATE_ADD: `${BASE_URL}/transTemplate/add`,
  TRANSTEMPLATE_UPDATE: `${BASE_URL}/transTemplate/update`,
  TRANSTEMPLATE_DELETE: `${BASE_URL}/transTemplate/delete`,
  /** OnlyOffice editor apis */
  EDIT_META: `${OPEN_URL}/oeditor-meta`,
  EDIT_API: `${OPEN_URL}/oeditor`,
  EDIT_CMND: `${OPEN_URL}/oeditor-cmnd`,

  GRAPH_PLAN_LIST: `${BASE_URL}/graph-plan/list`,
  GRAPH_PLAN_INFO: `${BASE_URL}/graph-plan/info`,
  GRAPH_PLAN_ADD: `${BASE_URL}/graph-plan/add`,
  GRAPH_PLAN_UPDATE: `${BASE_URL}/graph-plan/update`,
  GRAPH_PLAN_DELETE: `${BASE_URL}/graph-plan/delete`,
  GRAPH_PLAN_ITEM_LIST: `${BASE_URL}/graph-plan-item/list`,
  GRAPH_PLAN_ITEM_INFO: `${BASE_URL}/graph-plan-item/info`,
  GRAPH_PLAN_ITEM_ADD: `${BASE_URL}/graph-plan-item/add`,
  GRAPH_PLAN_ITEM_UPDATE: `${BASE_URL}/graph-plan-item/update`,
  GRAPH_PLAN_ITEM_DELETE: `${BASE_URL}/graph-plan-item/delete`,
  GRAPH_PLAN_ITEM_VERSION_LIST: `${BASE_URL}/graph-plan-item-version/list`,
  GRAPH_PLAN_ITEM_VERSION_DOWNLOAD: `${BASE_URL}/common/download-url`,
  CHECK_DESIGN_FILE: `${BASE_URL}/doc-plan-item/check`,

  OBJECT_DOWNLOAD: `${BASE_URL}/common/download-url`,
  GENERATE_TEXT: `${BASE_URL}/common/generate-text`,
  COMPLETE_TEXT: `${BASE_URL}/common/complete-text`,
  SAVE_EDITABLE_TEXT: `${BASE_URL}/common/save-editable-text`,
  OPEN_EDITABLE_TEXT: `${BASE_URL}/common/open-editable-text`,
  SAVE_SIGNATURE_TEXT: `${BASE_URL}/common/save-signature-text`,
  ZIP_DRCS: `${BASE_URL}/common/zip-drcs`,

  CONTRACTOR_OUT_DESIGN_LIST: `${BASE_URL}/contractor/design-list`,
  CONTRACTOR_OUT_GENERAL_LIST: `${BASE_URL}/contractor/general-list`,
  CONTRACTOR_INCOMING_LIST: `${BASE_URL}/contractor/incoming-list`,
  CONTRACTOR_TRANS_INFO: `${BASE_URL}/contractor/trans-info`,
  CONTRACTOR_TRANS_SAVE: `${BASE_URL}/contractor/trans-save`,
  CONTRACTOR_TRANS_SUBMIT: `${BASE_URL}/contractor/trans-submit`,
  CONTRACTOR_TRANS_REGISTE: `${BASE_URL}/contractor/trans-registe`,

  INCOMING_INFO: `${BASE_URL}/trans/info`,
  INCOMING_TODO_LIST: `${BASE_URL}/incoming-list/todo`,
  INCOMING_INPROCESS_LIST: `${BASE_URL}/incoming-list/in-process`,
  INCOMING_CCTOME_LIST: `${BASE_URL}/incoming-list/cc-to-me`,
  INCOMING_LIST: `${BASE_URL}/incoming-list/list`,
  INCOMING_ALL_LIST: `${BASE_URL}/incoming-list/all`,

  INCOMING_REGISTE: `${BASE_URL}/incoming/registe`,
  INCOMING_APPROVE: `${BASE_URL}/incoming/approve`,
  INCOMING_PROCESS: `${BASE_URL}/incoming/process`,
  INCOMING_MANUAL_REGISTE: `${BASE_URL}/incoming/manualRegiste`,
  INCOMING_DIRECT_RECEIVE_DOC: `${BASE_URL}/incoming/directReceive`,
  INCOMING_CCVIEW: `${BASE_URL}/incoming/ccview`,
  INCOMING_PRJ_MANAGER_APPROVE: `${BASE_URL}/incoming/prj-manager-approve`,
  INCOMING_DESIGN_MANAGER_APPROVE: `${BASE_URL}/incoming/design-manager-approve`,
  INCOMING_DESIGN_REVIEWER_REVIEW: `${BASE_URL}/incoming/reviewer-review`,
  INCOMING_DESIGN_DESIGN_MANAGER_REVIEW: `${BASE_URL}/incoming/design-manager-review`,
  INCOMING_DESIGN_PRJ_MANAGER_REVIEW: `${BASE_URL}/incoming/prj-manager-review`,
  INCOMING_DESIGN_REVIEW_HISTORY_LIST: `${BASE_URL}/incoming/review-history-list`,

  OUTGOING_INFO: `${BASE_URL}/trans/info`,
  OUTGOING_TODO_LIST: `${BASE_URL}/outgoing-list/todo`,
  OUTGOING_INPROCESS_LIST: `${BASE_URL}/outgoing-list/in-process`,
  OUTGOING_CCTOME_LIST: `${BASE_URL}/outgoing-list/cc-to-me`,
  OUTGOING_LIST: `${BASE_URL}/outgoing-list/list`,
  OUTGOING_ALL_LIST: `${BASE_URL}/outgoing-list/all`,

  OUTGOING_SAVE: `${BASE_URL}/outgoing/save`,
  OUTGOING_SUBMIT_APPROVAL: `${BASE_URL}/outgoing/submitApproval`,
  OUTGOING_APPROVE: `${BASE_URL}/outgoing/approve`,
  OUTGOING_SEND_DOC: `${BASE_URL}/outgoing/send`,
  OUTGOING_DIRECT_SEND_DOC: `${BASE_URL}/outgoing/directSend`,
  OUTGOING_SEND_OPINION: `${BASE_URL}/outgoing/send-opinion`,
  OUTGOING_CCVIEW: `${BASE_URL}/outgoing/ccview`,

  TRACK_PRJ_LIST: `${BASE_URL}/track/prj-list`,
  TRACK_ITEM_LIST: `${BASE_URL}/track/item-list`,
  TRACK_VERSION_LIST: `${BASE_URL}/track/version-list`,
  TRACK_ALL_VERSION_LIST: `${BASE_URL}/track/all-version-list`,
  TRACK_DOC_VER_LIST: `${BASE_URL}/track/all-doc-act-list`,

  // shangfan Add 20221206
  DOC_PLAN_LIST: `${BASE_URL}/doc-plan/list`,
  DOC_PLAN_EXPANT: `${BASE_URL}/doc-plan/expant`,
  DOC_PLAN_INFO: `${BASE_URL}/doc-plan/info`,
  DOC_PLAN_ADD: `${BASE_URL}/doc-plan/add`,
  DOC_PLAN_UPDATE: `${BASE_URL}/doc-plan/update`,
  DOC_PLAN_DELETE: `${BASE_URL}/doc-plan/delete`,
  DOC_PLAN_ROLLBACK: `${BASE_URL}/doc-plan/rollback`,
  DOC_PLAN_ITEM_LIST: `${BASE_URL}/doc-plan-item/list`,
  DOC_PLAN_ITEM_EXPANT: `${BASE_URL}/doc-plan-item/expant`,
  DOC_PLAN_ITEM_INFO: `${BASE_URL}/doc-plan-item/info`,
  DOC_PLAN_ITEM_ADD: `${BASE_URL}/doc-plan-item/add`,
  DOC_PLAN_ITEM_UPDATE: `${BASE_URL}/doc-plan-item/update`,
  DOC_PLAN_ITEM_DELETE: `${BASE_URL}/doc-plan-item/delete`,
  DOC_PLAN_ITEM_ROLLBACK: `${BASE_URL}/doc-plan-item/rollback`,
  DOC_ACT_LIST: `${BASE_URL}/doc-act/list`,

  // cabinet apis
  CAB_ENTRY_QUERY: `${BASE_URL}/cab/entry-query`,
  CAB_ENTRY_PERMS: `${BASE_URL}/cab/entry-perms`,
  CAB_CABINET_ADD: `${BASE_URL}/cab/cab-add`,
  CAB_CABINET_EDIT: `${BASE_URL}/cab/cab-edit`,
  CAB_CABINET_DEL: `${BASE_URL}/cab/cab-delete`,
  CAB_CABINET_INFO: `${BASE_URL}/cab/cab-info`,
  CAB_CABINET_QUERY: `${BASE_URL}/cab/cab-query`,
  CAB_FILE_ADD: `${BASE_URL}/cab/file-add`,
  CAB_FILE_SAVE: `${BASE_URL}/cab/file-save`,
  CAB_FILE_UPDATE: `${BASE_URL}/cab/file-update`,
  CAB_FILE_COPY: `${BASE_URL}/cab/file-copy`,
  CAB_FILE_MOVE: `${BASE_URL}/cab/file-move`,
  CAB_FILE_DEL: `${BASE_URL}/cab/file-delete`,
  CAB_FILE_INFO: `${BASE_URL}/cab/file-info`,
  CAB_FILE_GRANT: `${BASE_URL}/cab/file-grant`,
  CAB_FILE_REVOKE: `${BASE_URL}/cab/file-revoke`,
  CAB_FILE_DETECT: `${BASE_URL}/cab/file-detect`,
  CAB_FOLDER_ADD: `${BASE_URL}/cab/folder-add`,
  CAB_FOLDER_UPDATE: `${BASE_URL}/cab/folder-update`,
  CAB_FOLDER_COPY: `${BASE_URL}/cab/folder-copy`,
  CAB_FOLDER_MOVE: `${BASE_URL}/cab/folder-move`,
  CAB_FOLDER_DEL: `${BASE_URL}/cab/folder-delete`,
  CAB_FOLDER_GRANT: `${BASE_URL}/cab/folder-grant`,
  CAB_FOLDER_REVOKE: `${BASE_URL}/cab/folder-revoke`,
  CAB_REV_ADD: `${BASE_URL}/cab/revise-add`,
  CAB_REV_SWITCH: `${BASE_URL}/cab/revise-switch`,
  CAB_REV_QUERY: `${BASE_URL}/cab/revise-query`,
  CAB_REV_DEL: `${BASE_URL}/cab/revise-delete`,
  CAB_REV_ROLLBACK: `${BASE_URL}/cab/revise-rollback`,
  CAB_TRASH_QUERY: `${BASE_URL}/cab/trash-entries`,
  CAB_TRASH_RESTORE: `${BASE_URL}/cab/trash-restore`,
  CAB_TRASH_PURGE: `${BASE_URL}/cab/trash-purge`,
  CAB_USER_QUERY: `${BASE_URL}/cab/user-query`,
  CAB_GROUP_QUERY: `${BASE_URL}/cab/usergroup-query`,
};
